[build]
  command = "npm run build --prefix packages/private-client"
  publish = "packages/private-client/dist"  # Ensure this matches your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "packages/private-client/dist"
