# Public client deployment for Netlify
[build]
  command = "npm run build"
  publish = "packages/private-client/dist"  # Change this to the correct path

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Dev settings (for local Netlify dev server)
[dev]
  command = "npm run dev"
  port = 5173
  publish = "packages/private-client/dist"  # Change this to the correct path
