[build]
  command = "npm run build --prefix packages/public-client"
  publish = "packages/public-client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
