# Public client deployment for Netlify
[build]
  BASE = "packages/public-client"
  PUBLISH = "packages/public-client/dist"
  COMMAND = "npm run build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Dev settings (for local Netlify dev server)
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"